'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace nsCipPlanej
	
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="CipPlanej")>  _
	Partial Public Class dcCipPlanej
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub InsertCipHist(instance As CipHist)
    End Sub
    Partial Private Sub UpdateCipHist(instance As CipHist)
    End Sub
    Partial Private Sub DeleteCipHist(instance As CipHist)
    End Sub
    Partial Private Sub InsertCipPlanej(instance As CipPlanej)
    End Sub
    Partial Private Sub UpdateCipPlanej(instance As CipPlanej)
    End Sub
    Partial Private Sub DeleteCipPlanej(instance As CipPlanej)
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.Geral.My.MySettings.Default.csCipPlanej, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property CipHist() As System.Data.Linq.Table(Of CipHist)
			Get
				Return Me.GetTable(Of CipHist)
			End Get
		End Property
		
		Public ReadOnly Property CipPlanej() As System.Data.Linq.Table(Of CipPlanej)
			Get
				Return Me.GetTable(Of CipPlanej)
			End Get
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CipHist")>  _
	Partial Public Class CipHist
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _DataHora As String
		
		Private _RotaId As Integer
		
		Private _RecNum As Integer
		
		Private _Status As String
		
		Private _Blk0 As System.Nullable(Of Integer)
		
		Private _Blk0Tempo As System.Nullable(Of Integer)
		
		Private _Blk0SpTemp As System.Nullable(Of Integer)
		
		Private _Blk0SpCond As System.Nullable(Of Integer)
		
		Private _Blk1 As System.Nullable(Of Integer)
		
		Private _Blk1Tempo As System.Nullable(Of Integer)
		
		Private _Blk1SpTemp As System.Nullable(Of Integer)
		
		Private _Blk1SpCond As System.Nullable(Of Integer)
		
		Private _Blk2 As System.Nullable(Of Integer)
		
		Private _Blk2Tempo As System.Nullable(Of Integer)
		
		Private _Blk2SpTemp As System.Nullable(Of Integer)
		
		Private _Blk2SpCond As System.Nullable(Of Integer)
		
		Private _Blk3 As System.Nullable(Of Integer)
		
		Private _Blk3Tempo As System.Nullable(Of Integer)
		
		Private _Blk3SpTemp As System.Nullable(Of Integer)
		
		Private _Blk3SpCond As System.Nullable(Of Integer)
		
		Private _Blk4 As System.Nullable(Of Integer)
		
		Private _Blk4Tempo As System.Nullable(Of Integer)
		
		Private _Blk4SpTemp As System.Nullable(Of Integer)
		
		Private _Blk4SpCond As System.Nullable(Of Integer)
		
		Private _Blk5 As System.Nullable(Of Integer)
		
		Private _Blk5Tempo As System.Nullable(Of Integer)
		
		Private _Blk5SpTemp As System.Nullable(Of Integer)
		
		Private _Blk5SpCond As System.Nullable(Of Integer)
		
		Private _Blk6 As System.Nullable(Of Integer)
		
		Private _Blk6Tempo As System.Nullable(Of Integer)
		
		Private _Blk6SpTemp As System.Nullable(Of Integer)
		
		Private _Blk6SpCond As System.Nullable(Of Integer)
		
		Private _Blk7 As System.Nullable(Of Integer)
		
		Private _Blk7Tempo As System.Nullable(Of Integer)
		
		Private _Blk7SpTemp As System.Nullable(Of Integer)
		
		Private _Blk7SpCond As System.Nullable(Of Integer)
		
		Private _Blk8 As System.Nullable(Of Integer)
		
		Private _Blk8Tempo As System.Nullable(Of Integer)
		
		Private _Blk8SpTemp As System.Nullable(Of Integer)
		
		Private _Blk8SpCond As System.Nullable(Of Integer)
		
		Private _Blk9 As System.Nullable(Of Integer)
		
		Private _Blk9Tempo As System.Nullable(Of Integer)
		
		Private _Blk9SpTemp As System.Nullable(Of Integer)
		
		Private _Blk9SpCond As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnRotaIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnRotaIdChanged()
    End Sub
    Partial Private Sub OnRecNumChanging(value As Integer)
    End Sub
    Partial Private Sub OnRecNumChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As String)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnBlk0Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk0Changed()
    End Sub
    Partial Private Sub OnBlk0TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk0TempoChanged()
    End Sub
    Partial Private Sub OnBlk0SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk0SpTempChanged()
    End Sub
    Partial Private Sub OnBlk0SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk0SpCondChanged()
    End Sub
    Partial Private Sub OnBlk1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk1Changed()
    End Sub
    Partial Private Sub OnBlk1TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk1TempoChanged()
    End Sub
    Partial Private Sub OnBlk1SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk1SpTempChanged()
    End Sub
    Partial Private Sub OnBlk1SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk1SpCondChanged()
    End Sub
    Partial Private Sub OnBlk2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk2Changed()
    End Sub
    Partial Private Sub OnBlk2TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk2TempoChanged()
    End Sub
    Partial Private Sub OnBlk2SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk2SpTempChanged()
    End Sub
    Partial Private Sub OnBlk2SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk2SpCondChanged()
    End Sub
    Partial Private Sub OnBlk3Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk3Changed()
    End Sub
    Partial Private Sub OnBlk3TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk3TempoChanged()
    End Sub
    Partial Private Sub OnBlk3SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk3SpTempChanged()
    End Sub
    Partial Private Sub OnBlk3SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk3SpCondChanged()
    End Sub
    Partial Private Sub OnBlk4Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk4Changed()
    End Sub
    Partial Private Sub OnBlk4TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk4TempoChanged()
    End Sub
    Partial Private Sub OnBlk4SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk4SpTempChanged()
    End Sub
    Partial Private Sub OnBlk4SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk4SpCondChanged()
    End Sub
    Partial Private Sub OnBlk5Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk5Changed()
    End Sub
    Partial Private Sub OnBlk5TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk5TempoChanged()
    End Sub
    Partial Private Sub OnBlk5SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk5SpTempChanged()
    End Sub
    Partial Private Sub OnBlk5SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk5SpCondChanged()
    End Sub
    Partial Private Sub OnBlk6Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk6Changed()
    End Sub
    Partial Private Sub OnBlk6TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk6TempoChanged()
    End Sub
    Partial Private Sub OnBlk6SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk6SpTempChanged()
    End Sub
    Partial Private Sub OnBlk6SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk6SpCondChanged()
    End Sub
    Partial Private Sub OnBlk7Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk7Changed()
    End Sub
    Partial Private Sub OnBlk7TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk7TempoChanged()
    End Sub
    Partial Private Sub OnBlk7SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk7SpTempChanged()
    End Sub
    Partial Private Sub OnBlk7SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk7SpCondChanged()
    End Sub
    Partial Private Sub OnBlk8Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk8Changed()
    End Sub
    Partial Private Sub OnBlk8TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk8TempoChanged()
    End Sub
    Partial Private Sub OnBlk8SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk8SpTempChanged()
    End Sub
    Partial Private Sub OnBlk8SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk8SpCondChanged()
    End Sub
    Partial Private Sub OnBlk9Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk9Changed()
    End Sub
    Partial Private Sub OnBlk9TempoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk9TempoChanged()
    End Sub
    Partial Private Sub OnBlk9SpTempChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk9SpTempChanged()
    End Sub
    Partial Private Sub OnBlk9SpCondChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlk9SpCondChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RotaId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property RotaId() As Integer
			Get
				Return Me._RotaId
			End Get
			Set
				If ((Me._RotaId = value)  _
							= false) Then
					Me.OnRotaIdChanging(value)
					Me.SendPropertyChanging
					Me._RotaId = value
					Me.SendPropertyChanged("RotaId")
					Me.OnRotaIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecNum", DbType:="Int NOT NULL")>  _
		Public Property RecNum() As Integer
			Get
				Return Me._RecNum
			End Get
			Set
				If ((Me._RecNum = value)  _
							= false) Then
					Me.OnRecNumChanging(value)
					Me.SendPropertyChanging
					Me._RecNum = value
					Me.SendPropertyChanged("RecNum")
					Me.OnRecNumChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="NVarChar(1)")>  _
		Public Property Status() As String
			Get
				Return Me._Status
			End Get
			Set
				If (String.Equals(Me._Status, value) = false) Then
					Me.OnStatusChanging(value)
					Me.SendPropertyChanging
					Me._Status = value
					Me.SendPropertyChanged("Status")
					Me.OnStatusChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk0", DbType:="Int")>  _
		Public Property Blk0() As System.Nullable(Of Integer)
			Get
				Return Me._Blk0
			End Get
			Set
				If (Me._Blk0.Equals(value) = false) Then
					Me.OnBlk0Changing(value)
					Me.SendPropertyChanging
					Me._Blk0 = value
					Me.SendPropertyChanged("Blk0")
					Me.OnBlk0Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk0Tempo", DbType:="Int")>  _
		Public Property Blk0Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk0Tempo
			End Get
			Set
				If (Me._Blk0Tempo.Equals(value) = false) Then
					Me.OnBlk0TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk0Tempo = value
					Me.SendPropertyChanged("Blk0Tempo")
					Me.OnBlk0TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk0SpTemp", DbType:="Int")>  _
		Public Property Blk0SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk0SpTemp
			End Get
			Set
				If (Me._Blk0SpTemp.Equals(value) = false) Then
					Me.OnBlk0SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk0SpTemp = value
					Me.SendPropertyChanged("Blk0SpTemp")
					Me.OnBlk0SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk0SpCond", DbType:="Int")>  _
		Public Property Blk0SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk0SpCond
			End Get
			Set
				If (Me._Blk0SpCond.Equals(value) = false) Then
					Me.OnBlk0SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk0SpCond = value
					Me.SendPropertyChanged("Blk0SpCond")
					Me.OnBlk0SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk1", DbType:="Int")>  _
		Public Property Blk1() As System.Nullable(Of Integer)
			Get
				Return Me._Blk1
			End Get
			Set
				If (Me._Blk1.Equals(value) = false) Then
					Me.OnBlk1Changing(value)
					Me.SendPropertyChanging
					Me._Blk1 = value
					Me.SendPropertyChanged("Blk1")
					Me.OnBlk1Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk1Tempo", DbType:="Int")>  _
		Public Property Blk1Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk1Tempo
			End Get
			Set
				If (Me._Blk1Tempo.Equals(value) = false) Then
					Me.OnBlk1TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk1Tempo = value
					Me.SendPropertyChanged("Blk1Tempo")
					Me.OnBlk1TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk1SpTemp", DbType:="Int")>  _
		Public Property Blk1SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk1SpTemp
			End Get
			Set
				If (Me._Blk1SpTemp.Equals(value) = false) Then
					Me.OnBlk1SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk1SpTemp = value
					Me.SendPropertyChanged("Blk1SpTemp")
					Me.OnBlk1SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk1SpCond", DbType:="Int")>  _
		Public Property Blk1SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk1SpCond
			End Get
			Set
				If (Me._Blk1SpCond.Equals(value) = false) Then
					Me.OnBlk1SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk1SpCond = value
					Me.SendPropertyChanged("Blk1SpCond")
					Me.OnBlk1SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk2", DbType:="Int")>  _
		Public Property Blk2() As System.Nullable(Of Integer)
			Get
				Return Me._Blk2
			End Get
			Set
				If (Me._Blk2.Equals(value) = false) Then
					Me.OnBlk2Changing(value)
					Me.SendPropertyChanging
					Me._Blk2 = value
					Me.SendPropertyChanged("Blk2")
					Me.OnBlk2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk2Tempo", DbType:="Int")>  _
		Public Property Blk2Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk2Tempo
			End Get
			Set
				If (Me._Blk2Tempo.Equals(value) = false) Then
					Me.OnBlk2TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk2Tempo = value
					Me.SendPropertyChanged("Blk2Tempo")
					Me.OnBlk2TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk2SpTemp", DbType:="Int")>  _
		Public Property Blk2SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk2SpTemp
			End Get
			Set
				If (Me._Blk2SpTemp.Equals(value) = false) Then
					Me.OnBlk2SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk2SpTemp = value
					Me.SendPropertyChanged("Blk2SpTemp")
					Me.OnBlk2SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk2SpCond", DbType:="Int")>  _
		Public Property Blk2SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk2SpCond
			End Get
			Set
				If (Me._Blk2SpCond.Equals(value) = false) Then
					Me.OnBlk2SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk2SpCond = value
					Me.SendPropertyChanged("Blk2SpCond")
					Me.OnBlk2SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk3", DbType:="Int")>  _
		Public Property Blk3() As System.Nullable(Of Integer)
			Get
				Return Me._Blk3
			End Get
			Set
				If (Me._Blk3.Equals(value) = false) Then
					Me.OnBlk3Changing(value)
					Me.SendPropertyChanging
					Me._Blk3 = value
					Me.SendPropertyChanged("Blk3")
					Me.OnBlk3Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk3Tempo", DbType:="Int")>  _
		Public Property Blk3Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk3Tempo
			End Get
			Set
				If (Me._Blk3Tempo.Equals(value) = false) Then
					Me.OnBlk3TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk3Tempo = value
					Me.SendPropertyChanged("Blk3Tempo")
					Me.OnBlk3TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk3SpTemp", DbType:="Int")>  _
		Public Property Blk3SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk3SpTemp
			End Get
			Set
				If (Me._Blk3SpTemp.Equals(value) = false) Then
					Me.OnBlk3SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk3SpTemp = value
					Me.SendPropertyChanged("Blk3SpTemp")
					Me.OnBlk3SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk3SpCond", DbType:="Int")>  _
		Public Property Blk3SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk3SpCond
			End Get
			Set
				If (Me._Blk3SpCond.Equals(value) = false) Then
					Me.OnBlk3SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk3SpCond = value
					Me.SendPropertyChanged("Blk3SpCond")
					Me.OnBlk3SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk4", DbType:="Int")>  _
		Public Property Blk4() As System.Nullable(Of Integer)
			Get
				Return Me._Blk4
			End Get
			Set
				If (Me._Blk4.Equals(value) = false) Then
					Me.OnBlk4Changing(value)
					Me.SendPropertyChanging
					Me._Blk4 = value
					Me.SendPropertyChanged("Blk4")
					Me.OnBlk4Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk4Tempo", DbType:="Int")>  _
		Public Property Blk4Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk4Tempo
			End Get
			Set
				If (Me._Blk4Tempo.Equals(value) = false) Then
					Me.OnBlk4TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk4Tempo = value
					Me.SendPropertyChanged("Blk4Tempo")
					Me.OnBlk4TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk4SpTemp", DbType:="Int")>  _
		Public Property Blk4SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk4SpTemp
			End Get
			Set
				If (Me._Blk4SpTemp.Equals(value) = false) Then
					Me.OnBlk4SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk4SpTemp = value
					Me.SendPropertyChanged("Blk4SpTemp")
					Me.OnBlk4SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk4SpCond", DbType:="Int")>  _
		Public Property Blk4SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk4SpCond
			End Get
			Set
				If (Me._Blk4SpCond.Equals(value) = false) Then
					Me.OnBlk4SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk4SpCond = value
					Me.SendPropertyChanged("Blk4SpCond")
					Me.OnBlk4SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk5", DbType:="Int")>  _
		Public Property Blk5() As System.Nullable(Of Integer)
			Get
				Return Me._Blk5
			End Get
			Set
				If (Me._Blk5.Equals(value) = false) Then
					Me.OnBlk5Changing(value)
					Me.SendPropertyChanging
					Me._Blk5 = value
					Me.SendPropertyChanged("Blk5")
					Me.OnBlk5Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk5Tempo", DbType:="Int")>  _
		Public Property Blk5Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk5Tempo
			End Get
			Set
				If (Me._Blk5Tempo.Equals(value) = false) Then
					Me.OnBlk5TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk5Tempo = value
					Me.SendPropertyChanged("Blk5Tempo")
					Me.OnBlk5TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk5SpTemp", DbType:="Int")>  _
		Public Property Blk5SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk5SpTemp
			End Get
			Set
				If (Me._Blk5SpTemp.Equals(value) = false) Then
					Me.OnBlk5SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk5SpTemp = value
					Me.SendPropertyChanged("Blk5SpTemp")
					Me.OnBlk5SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk5SpCond", DbType:="Int")>  _
		Public Property Blk5SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk5SpCond
			End Get
			Set
				If (Me._Blk5SpCond.Equals(value) = false) Then
					Me.OnBlk5SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk5SpCond = value
					Me.SendPropertyChanged("Blk5SpCond")
					Me.OnBlk5SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk6", DbType:="Int")>  _
		Public Property Blk6() As System.Nullable(Of Integer)
			Get
				Return Me._Blk6
			End Get
			Set
				If (Me._Blk6.Equals(value) = false) Then
					Me.OnBlk6Changing(value)
					Me.SendPropertyChanging
					Me._Blk6 = value
					Me.SendPropertyChanged("Blk6")
					Me.OnBlk6Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk6Tempo", DbType:="Int")>  _
		Public Property Blk6Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk6Tempo
			End Get
			Set
				If (Me._Blk6Tempo.Equals(value) = false) Then
					Me.OnBlk6TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk6Tempo = value
					Me.SendPropertyChanged("Blk6Tempo")
					Me.OnBlk6TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk6SpTemp", DbType:="Int")>  _
		Public Property Blk6SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk6SpTemp
			End Get
			Set
				If (Me._Blk6SpTemp.Equals(value) = false) Then
					Me.OnBlk6SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk6SpTemp = value
					Me.SendPropertyChanged("Blk6SpTemp")
					Me.OnBlk6SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk6SpCond", DbType:="Int")>  _
		Public Property Blk6SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk6SpCond
			End Get
			Set
				If (Me._Blk6SpCond.Equals(value) = false) Then
					Me.OnBlk6SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk6SpCond = value
					Me.SendPropertyChanged("Blk6SpCond")
					Me.OnBlk6SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk7", DbType:="Int")>  _
		Public Property Blk7() As System.Nullable(Of Integer)
			Get
				Return Me._Blk7
			End Get
			Set
				If (Me._Blk7.Equals(value) = false) Then
					Me.OnBlk7Changing(value)
					Me.SendPropertyChanging
					Me._Blk7 = value
					Me.SendPropertyChanged("Blk7")
					Me.OnBlk7Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk7Tempo", DbType:="Int")>  _
		Public Property Blk7Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk7Tempo
			End Get
			Set
				If (Me._Blk7Tempo.Equals(value) = false) Then
					Me.OnBlk7TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk7Tempo = value
					Me.SendPropertyChanged("Blk7Tempo")
					Me.OnBlk7TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk7SpTemp", DbType:="Int")>  _
		Public Property Blk7SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk7SpTemp
			End Get
			Set
				If (Me._Blk7SpTemp.Equals(value) = false) Then
					Me.OnBlk7SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk7SpTemp = value
					Me.SendPropertyChanged("Blk7SpTemp")
					Me.OnBlk7SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk7SpCond", DbType:="Int")>  _
		Public Property Blk7SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk7SpCond
			End Get
			Set
				If (Me._Blk7SpCond.Equals(value) = false) Then
					Me.OnBlk7SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk7SpCond = value
					Me.SendPropertyChanged("Blk7SpCond")
					Me.OnBlk7SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk8", DbType:="Int")>  _
		Public Property Blk8() As System.Nullable(Of Integer)
			Get
				Return Me._Blk8
			End Get
			Set
				If (Me._Blk8.Equals(value) = false) Then
					Me.OnBlk8Changing(value)
					Me.SendPropertyChanging
					Me._Blk8 = value
					Me.SendPropertyChanged("Blk8")
					Me.OnBlk8Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk8Tempo", DbType:="Int")>  _
		Public Property Blk8Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk8Tempo
			End Get
			Set
				If (Me._Blk8Tempo.Equals(value) = false) Then
					Me.OnBlk8TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk8Tempo = value
					Me.SendPropertyChanged("Blk8Tempo")
					Me.OnBlk8TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk8SpTemp", DbType:="Int")>  _
		Public Property Blk8SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk8SpTemp
			End Get
			Set
				If (Me._Blk8SpTemp.Equals(value) = false) Then
					Me.OnBlk8SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk8SpTemp = value
					Me.SendPropertyChanged("Blk8SpTemp")
					Me.OnBlk8SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk8SpCond", DbType:="Int")>  _
		Public Property Blk8SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk8SpCond
			End Get
			Set
				If (Me._Blk8SpCond.Equals(value) = false) Then
					Me.OnBlk8SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk8SpCond = value
					Me.SendPropertyChanged("Blk8SpCond")
					Me.OnBlk8SpCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk9", DbType:="Int")>  _
		Public Property Blk9() As System.Nullable(Of Integer)
			Get
				Return Me._Blk9
			End Get
			Set
				If (Me._Blk9.Equals(value) = false) Then
					Me.OnBlk9Changing(value)
					Me.SendPropertyChanging
					Me._Blk9 = value
					Me.SendPropertyChanged("Blk9")
					Me.OnBlk9Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk9Tempo", DbType:="Int")>  _
		Public Property Blk9Tempo() As System.Nullable(Of Integer)
			Get
				Return Me._Blk9Tempo
			End Get
			Set
				If (Me._Blk9Tempo.Equals(value) = false) Then
					Me.OnBlk9TempoChanging(value)
					Me.SendPropertyChanging
					Me._Blk9Tempo = value
					Me.SendPropertyChanged("Blk9Tempo")
					Me.OnBlk9TempoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk9SpTemp", DbType:="Int")>  _
		Public Property Blk9SpTemp() As System.Nullable(Of Integer)
			Get
				Return Me._Blk9SpTemp
			End Get
			Set
				If (Me._Blk9SpTemp.Equals(value) = false) Then
					Me.OnBlk9SpTempChanging(value)
					Me.SendPropertyChanging
					Me._Blk9SpTemp = value
					Me.SendPropertyChanged("Blk9SpTemp")
					Me.OnBlk9SpTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk9SpCond", DbType:="Int")>  _
		Public Property Blk9SpCond() As System.Nullable(Of Integer)
			Get
				Return Me._Blk9SpCond
			End Get
			Set
				If (Me._Blk9SpCond.Equals(value) = false) Then
					Me.OnBlk9SpCondChanging(value)
					Me.SendPropertyChanging
					Me._Blk9SpCond = value
					Me.SendPropertyChanged("Blk9SpCond")
					Me.OnBlk9SpCondChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CipPlanej")>  _
	Partial Public Class CipPlanej
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _Circ As String
		
		Private _RotaId As Integer
		
		Private _RecNum As Integer
		
		Private _Sequencia As System.Nullable(Of Integer)
		
		Private _SubRota1 As System.Nullable(Of Integer)
		
		Private _SubRota2 As System.Nullable(Of Integer)
		
		Private _SubRota3 As System.Nullable(Of Integer)
		
		Private _SubRota4 As System.Nullable(Of Integer)
		
		Private _SubRota5 As System.Nullable(Of Integer)
		
		Private _SubRota6 As System.Nullable(Of Integer)
		
		Private _SubRota7 As System.Nullable(Of Integer)
		
		Private _SubRota8 As System.Nullable(Of Integer)
		
		Private _SubRota9 As System.Nullable(Of Integer)
		
		Private _SubRota10 As System.Nullable(Of Integer)
		
		Private _BbaCipFw As System.Nullable(Of Double)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCircChanging(value As String)
    End Sub
    Partial Private Sub OnCircChanged()
    End Sub
    Partial Private Sub OnRotaIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnRotaIdChanged()
    End Sub
    Partial Private Sub OnRecNumChanging(value As Integer)
    End Sub
    Partial Private Sub OnRecNumChanged()
    End Sub
    Partial Private Sub OnSequenciaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSequenciaChanged()
    End Sub
    Partial Private Sub OnSubRota1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota1Changed()
    End Sub
    Partial Private Sub OnSubRota2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota2Changed()
    End Sub
    Partial Private Sub OnSubRota3Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota3Changed()
    End Sub
    Partial Private Sub OnSubRota4Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota4Changed()
    End Sub
    Partial Private Sub OnSubRota5Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota5Changed()
    End Sub
    Partial Private Sub OnSubRota6Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota6Changed()
    End Sub
    Partial Private Sub OnSubRota7Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota7Changed()
    End Sub
    Partial Private Sub OnSubRota8Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota8Changed()
    End Sub
    Partial Private Sub OnSubRota9Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota9Changed()
    End Sub
    Partial Private Sub OnSubRota10Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSubRota10Changed()
    End Sub
    Partial Private Sub OnBbaCipFwChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnBbaCipFwChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Circ", DbType:="NVarChar(1) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property Circ() As String
			Get
				Return Me._Circ
			End Get
			Set
				If (String.Equals(Me._Circ, value) = false) Then
					Me.OnCircChanging(value)
					Me.SendPropertyChanging
					Me._Circ = value
					Me.SendPropertyChanged("Circ")
					Me.OnCircChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RotaId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property RotaId() As Integer
			Get
				Return Me._RotaId
			End Get
			Set
				If ((Me._RotaId = value)  _
							= false) Then
					Me.OnRotaIdChanging(value)
					Me.SendPropertyChanging
					Me._RotaId = value
					Me.SendPropertyChanged("RotaId")
					Me.OnRotaIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecNum", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property RecNum() As Integer
			Get
				Return Me._RecNum
			End Get
			Set
				If ((Me._RecNum = value)  _
							= false) Then
					Me.OnRecNumChanging(value)
					Me.SendPropertyChanging
					Me._RecNum = value
					Me.SendPropertyChanged("RecNum")
					Me.OnRecNumChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Sequencia", DbType:="Int")>  _
		Public Property Sequencia() As System.Nullable(Of Integer)
			Get
				Return Me._Sequencia
			End Get
			Set
				If (Me._Sequencia.Equals(value) = false) Then
					Me.OnSequenciaChanging(value)
					Me.SendPropertyChanging
					Me._Sequencia = value
					Me.SendPropertyChanged("Sequencia")
					Me.OnSequenciaChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota1", DbType:="Int")>  _
		Public Property SubRota1() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota1
			End Get
			Set
				If (Me._SubRota1.Equals(value) = false) Then
					Me.OnSubRota1Changing(value)
					Me.SendPropertyChanging
					Me._SubRota1 = value
					Me.SendPropertyChanged("SubRota1")
					Me.OnSubRota1Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota2", DbType:="Int")>  _
		Public Property SubRota2() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota2
			End Get
			Set
				If (Me._SubRota2.Equals(value) = false) Then
					Me.OnSubRota2Changing(value)
					Me.SendPropertyChanging
					Me._SubRota2 = value
					Me.SendPropertyChanged("SubRota2")
					Me.OnSubRota2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota3", DbType:="Int")>  _
		Public Property SubRota3() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota3
			End Get
			Set
				If (Me._SubRota3.Equals(value) = false) Then
					Me.OnSubRota3Changing(value)
					Me.SendPropertyChanging
					Me._SubRota3 = value
					Me.SendPropertyChanged("SubRota3")
					Me.OnSubRota3Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota4", DbType:="Int")>  _
		Public Property SubRota4() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota4
			End Get
			Set
				If (Me._SubRota4.Equals(value) = false) Then
					Me.OnSubRota4Changing(value)
					Me.SendPropertyChanging
					Me._SubRota4 = value
					Me.SendPropertyChanged("SubRota4")
					Me.OnSubRota4Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota5", DbType:="Int")>  _
		Public Property SubRota5() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota5
			End Get
			Set
				If (Me._SubRota5.Equals(value) = false) Then
					Me.OnSubRota5Changing(value)
					Me.SendPropertyChanging
					Me._SubRota5 = value
					Me.SendPropertyChanged("SubRota5")
					Me.OnSubRota5Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota6", DbType:="Int")>  _
		Public Property SubRota6() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota6
			End Get
			Set
				If (Me._SubRota6.Equals(value) = false) Then
					Me.OnSubRota6Changing(value)
					Me.SendPropertyChanging
					Me._SubRota6 = value
					Me.SendPropertyChanged("SubRota6")
					Me.OnSubRota6Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota7", DbType:="Int")>  _
		Public Property SubRota7() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota7
			End Get
			Set
				If (Me._SubRota7.Equals(value) = false) Then
					Me.OnSubRota7Changing(value)
					Me.SendPropertyChanging
					Me._SubRota7 = value
					Me.SendPropertyChanged("SubRota7")
					Me.OnSubRota7Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota8", DbType:="Int")>  _
		Public Property SubRota8() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota8
			End Get
			Set
				If (Me._SubRota8.Equals(value) = false) Then
					Me.OnSubRota8Changing(value)
					Me.SendPropertyChanging
					Me._SubRota8 = value
					Me.SendPropertyChanged("SubRota8")
					Me.OnSubRota8Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota9", DbType:="Int")>  _
		Public Property SubRota9() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota9
			End Get
			Set
				If (Me._SubRota9.Equals(value) = false) Then
					Me.OnSubRota9Changing(value)
					Me.SendPropertyChanging
					Me._SubRota9 = value
					Me.SendPropertyChanged("SubRota9")
					Me.OnSubRota9Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubRota10", DbType:="Int")>  _
		Public Property SubRota10() As System.Nullable(Of Integer)
			Get
				Return Me._SubRota10
			End Get
			Set
				If (Me._SubRota10.Equals(value) = false) Then
					Me.OnSubRota10Changing(value)
					Me.SendPropertyChanging
					Me._SubRota10 = value
					Me.SendPropertyChanged("SubRota10")
					Me.OnSubRota10Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BbaCipFw", DbType:="Float")>  _
		Public Property BbaCipFw() As System.Nullable(Of Double)
			Get
				Return Me._BbaCipFw
			End Get
			Set
				If (Me._BbaCipFw.Equals(value) = false) Then
					Me.OnBbaCipFwChanging(value)
					Me.SendPropertyChanging
					Me._BbaCipFw = value
					Me.SendPropertyChanged("BbaCipFw")
					Me.OnBbaCipFwChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
