'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace nsPastGrava
	
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PastGrava")>  _
	Partial Public Class dcPastGrava
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub InsertCfg(instance As Cfg)
    End Sub
    Partial Private Sub UpdateCfg(instance As Cfg)
    End Sub
    Partial Private Sub DeleteCfg(instance As Cfg)
    End Sub
    Partial Private Sub InsertPastGravaHistDadosBk(instance As PastGravaHistDadosBk)
    End Sub
    Partial Private Sub UpdatePastGravaHistDadosBk(instance As PastGravaHistDadosBk)
    End Sub
    Partial Private Sub DeletePastGravaHistDadosBk(instance As PastGravaHistDadosBk)
    End Sub
    Partial Private Sub InsertFdvGravaHist(instance As FdvGravaHist)
    End Sub
    Partial Private Sub UpdateFdvGravaHist(instance As FdvGravaHist)
    End Sub
    Partial Private Sub DeleteFdvGravaHist(instance As FdvGravaHist)
    End Sub
    Partial Private Sub InsertFdvGravaHistDados(instance As FdvGravaHistDados)
    End Sub
    Partial Private Sub UpdateFdvGravaHistDados(instance As FdvGravaHistDados)
    End Sub
    Partial Private Sub DeleteFdvGravaHistDados(instance As FdvGravaHistDados)
    End Sub
    Partial Private Sub InsertPastGravaHist(instance As PastGravaHist)
    End Sub
    Partial Private Sub UpdatePastGravaHist(instance As PastGravaHist)
    End Sub
    Partial Private Sub DeletePastGravaHist(instance As PastGravaHist)
    End Sub
    Partial Private Sub InsertPastGravaHistDados(instance As PastGravaHistDados)
    End Sub
    Partial Private Sub UpdatePastGravaHistDados(instance As PastGravaHistDados)
    End Sub
    Partial Private Sub DeletePastGravaHistDados(instance As PastGravaHistDados)
    End Sub
    Partial Private Sub InsertCipGravaHist(instance As CipGravaHist)
    End Sub
    Partial Private Sub UpdateCipGravaHist(instance As CipGravaHist)
    End Sub
    Partial Private Sub DeleteCipGravaHist(instance As CipGravaHist)
    End Sub
    Partial Private Sub InsertCipGravaHistDados(instance As CipGravaHistDados)
    End Sub
    Partial Private Sub UpdateCipGravaHistDados(instance As CipGravaHistDados)
    End Sub
    Partial Private Sub DeleteCipGravaHistDados(instance As CipGravaHistDados)
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.Geral.My.MySettings.Default.csPastGrava, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property Cfg() As System.Data.Linq.Table(Of Cfg)
			Get
				Return Me.GetTable(Of Cfg)
			End Get
		End Property
		
		Public ReadOnly Property PastGravaHistDadosBk() As System.Data.Linq.Table(Of PastGravaHistDadosBk)
			Get
				Return Me.GetTable(Of PastGravaHistDadosBk)
			End Get
		End Property
		
		Public ReadOnly Property FdvGravaHist() As System.Data.Linq.Table(Of FdvGravaHist)
			Get
				Return Me.GetTable(Of FdvGravaHist)
			End Get
		End Property
		
		Public ReadOnly Property FdvGravaHistDados() As System.Data.Linq.Table(Of FdvGravaHistDados)
			Get
				Return Me.GetTable(Of FdvGravaHistDados)
			End Get
		End Property
		
		Public ReadOnly Property PastGravaHist() As System.Data.Linq.Table(Of PastGravaHist)
			Get
				Return Me.GetTable(Of PastGravaHist)
			End Get
		End Property
		
		Public ReadOnly Property PastGravaHistDados() As System.Data.Linq.Table(Of PastGravaHistDados)
			Get
				Return Me.GetTable(Of PastGravaHistDados)
			End Get
		End Property
		
		Public ReadOnly Property CipGravaHist() As System.Data.Linq.Table(Of CipGravaHist)
			Get
				Return Me.GetTable(Of CipGravaHist)
			End Get
		End Property
		
		Public ReadOnly Property CipGravaHistDados() As System.Data.Linq.Table(Of CipGravaHistDados)
			Get
				Return Me.GetTable(Of CipGravaHistDados)
			End Get
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Cfg")>  _
	Partial Public Class Cfg
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _Item As String
		
		Private _Valor As String
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnItemChanging(value As String)
    End Sub
    Partial Private Sub OnItemChanged()
    End Sub
    Partial Private Sub OnValorChanging(value As String)
    End Sub
    Partial Private Sub OnValorChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property Item() As String
			Get
				Return Me._Item
			End Get
			Set
				If (String.Equals(Me._Item, value) = false) Then
					Me.OnItemChanging(value)
					Me.SendPropertyChanging
					Me._Item = value
					Me.SendPropertyChanged("Item")
					Me.OnItemChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Valor", DbType:="NVarChar(50)")>  _
		Public Property Valor() As String
			Get
				Return Me._Valor
			End Get
			Set
				If (String.Equals(Me._Valor, value) = false) Then
					Me.OnValorChanging(value)
					Me.SendPropertyChanging
					Me._Valor = value
					Me.SendPropertyChanged("Valor")
					Me.OnValorChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.PastGravaHistDadosBk")>  _
	Partial Public Class PastGravaHistDadosBk
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _HistId As Integer
		
		Private _DataHora As String
		
		Private _Sts As System.Nullable(Of Integer)
		
		Private _RecNum As System.Nullable(Of Integer)
		
		Private _TqOrig As System.Nullable(Of Integer)
		
		Private _TqDest As System.Nullable(Of Integer)
		
		Private _PressaoEst1 As System.Nullable(Of Single)
		
		Private _PressaoEst2 As System.Nullable(Of Single)
		
		Private _TempFdvPv As System.Nullable(Of Single)
		
		Private _TempFdvSp As System.Nullable(Of Single)
		
		Private _TempFinalPast As System.Nullable(Of Single)
		
		Private _PresFinalPast As System.Nullable(Of Single)
		
		Private _ValvFdvA As System.Nullable(Of Single)
		
		Private _ValvFdvB As System.Nullable(Of Single)
		
		Private _PresHomoEntr As System.Nullable(Of Single)
		
		Private _PresHomoSaida As System.Nullable(Of Single)
		
		Private _TempAguaAlcool As System.Nullable(Of Single)
		
		Private _Reserva2 As System.Nullable(Of Single)
		
		Private _Reserva3 As System.Nullable(Of Single)
		
		Private _Reserva4 As System.Nullable(Of Single)
		
		Private _Reserva5 As System.Nullable(Of Single)
		
		Private _Reserva6 As System.Nullable(Of Single)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnHistIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnHistIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnStsChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStsChanged()
    End Sub
    Partial Private Sub OnRecNumChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRecNumChanged()
    End Sub
    Partial Private Sub OnTqOrigChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTqOrigChanged()
    End Sub
    Partial Private Sub OnTqDestChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTqDestChanged()
    End Sub
    Partial Private Sub OnPressaoEst1Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPressaoEst1Changed()
    End Sub
    Partial Private Sub OnPressaoEst2Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPressaoEst2Changed()
    End Sub
    Partial Private Sub OnTempFdvPvChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvPvChanged()
    End Sub
    Partial Private Sub OnTempFdvSpChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvSpChanged()
    End Sub
    Partial Private Sub OnTempFinalPastChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFinalPastChanged()
    End Sub
    Partial Private Sub OnPresFinalPastChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresFinalPastChanged()
    End Sub
    Partial Private Sub OnValvFdvAChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnValvFdvAChanged()
    End Sub
    Partial Private Sub OnValvFdvBChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnValvFdvBChanged()
    End Sub
    Partial Private Sub OnPresHomoEntrChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresHomoEntrChanged()
    End Sub
    Partial Private Sub OnPresHomoSaidaChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresHomoSaidaChanged()
    End Sub
    Partial Private Sub OnTempAguaAlcoolChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempAguaAlcoolChanged()
    End Sub
    Partial Private Sub OnReserva2Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva2Changed()
    End Sub
    Partial Private Sub OnReserva3Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva3Changed()
    End Sub
    Partial Private Sub OnReserva4Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva4Changed()
    End Sub
    Partial Private Sub OnReserva5Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva5Changed()
    End Sub
    Partial Private Sub OnReserva6Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva6Changed()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HistId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property HistId() As Integer
			Get
				Return Me._HistId
			End Get
			Set
				If ((Me._HistId = value)  _
							= false) Then
					Me.OnHistIdChanging(value)
					Me.SendPropertyChanging
					Me._HistId = value
					Me.SendPropertyChanged("HistId")
					Me.OnHistIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Sts", DbType:="Int")>  _
		Public Property Sts() As System.Nullable(Of Integer)
			Get
				Return Me._Sts
			End Get
			Set
				If (Me._Sts.Equals(value) = false) Then
					Me.OnStsChanging(value)
					Me.SendPropertyChanging
					Me._Sts = value
					Me.SendPropertyChanged("Sts")
					Me.OnStsChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecNum", DbType:="Int")>  _
		Public Property RecNum() As System.Nullable(Of Integer)
			Get
				Return Me._RecNum
			End Get
			Set
				If (Me._RecNum.Equals(value) = false) Then
					Me.OnRecNumChanging(value)
					Me.SendPropertyChanging
					Me._RecNum = value
					Me.SendPropertyChanged("RecNum")
					Me.OnRecNumChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TqOrig", DbType:="Int")>  _
		Public Property TqOrig() As System.Nullable(Of Integer)
			Get
				Return Me._TqOrig
			End Get
			Set
				If (Me._TqOrig.Equals(value) = false) Then
					Me.OnTqOrigChanging(value)
					Me.SendPropertyChanging
					Me._TqOrig = value
					Me.SendPropertyChanged("TqOrig")
					Me.OnTqOrigChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TqDest", DbType:="Int")>  _
		Public Property TqDest() As System.Nullable(Of Integer)
			Get
				Return Me._TqDest
			End Get
			Set
				If (Me._TqDest.Equals(value) = false) Then
					Me.OnTqDestChanging(value)
					Me.SendPropertyChanging
					Me._TqDest = value
					Me.SendPropertyChanged("TqDest")
					Me.OnTqDestChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PressaoEst1", DbType:="Real")>  _
		Public Property PressaoEst1() As System.Nullable(Of Single)
			Get
				Return Me._PressaoEst1
			End Get
			Set
				If (Me._PressaoEst1.Equals(value) = false) Then
					Me.OnPressaoEst1Changing(value)
					Me.SendPropertyChanging
					Me._PressaoEst1 = value
					Me.SendPropertyChanged("PressaoEst1")
					Me.OnPressaoEst1Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PressaoEst2", DbType:="Real")>  _
		Public Property PressaoEst2() As System.Nullable(Of Single)
			Get
				Return Me._PressaoEst2
			End Get
			Set
				If (Me._PressaoEst2.Equals(value) = false) Then
					Me.OnPressaoEst2Changing(value)
					Me.SendPropertyChanging
					Me._PressaoEst2 = value
					Me.SendPropertyChanged("PressaoEst2")
					Me.OnPressaoEst2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvPv", DbType:="Real")>  _
		Public Property TempFdvPv() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvPv
			End Get
			Set
				If (Me._TempFdvPv.Equals(value) = false) Then
					Me.OnTempFdvPvChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvPv = value
					Me.SendPropertyChanged("TempFdvPv")
					Me.OnTempFdvPvChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvSp", DbType:="Real")>  _
		Public Property TempFdvSp() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvSp
			End Get
			Set
				If (Me._TempFdvSp.Equals(value) = false) Then
					Me.OnTempFdvSpChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvSp = value
					Me.SendPropertyChanged("TempFdvSp")
					Me.OnTempFdvSpChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFinalPast", DbType:="Real")>  _
		Public Property TempFinalPast() As System.Nullable(Of Single)
			Get
				Return Me._TempFinalPast
			End Get
			Set
				If (Me._TempFinalPast.Equals(value) = false) Then
					Me.OnTempFinalPastChanging(value)
					Me.SendPropertyChanging
					Me._TempFinalPast = value
					Me.SendPropertyChanged("TempFinalPast")
					Me.OnTempFinalPastChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresFinalPast", DbType:="Real")>  _
		Public Property PresFinalPast() As System.Nullable(Of Single)
			Get
				Return Me._PresFinalPast
			End Get
			Set
				If (Me._PresFinalPast.Equals(value) = false) Then
					Me.OnPresFinalPastChanging(value)
					Me.SendPropertyChanging
					Me._PresFinalPast = value
					Me.SendPropertyChanged("PresFinalPast")
					Me.OnPresFinalPastChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvA", DbType:="Real")>  _
		Public Property ValvFdvA() As System.Nullable(Of Single)
			Get
				Return Me._ValvFdvA
			End Get
			Set
				If (Me._ValvFdvA.Equals(value) = false) Then
					Me.OnValvFdvAChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvA = value
					Me.SendPropertyChanged("ValvFdvA")
					Me.OnValvFdvAChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvB", DbType:="Real")>  _
		Public Property ValvFdvB() As System.Nullable(Of Single)
			Get
				Return Me._ValvFdvB
			End Get
			Set
				If (Me._ValvFdvB.Equals(value) = false) Then
					Me.OnValvFdvBChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvB = value
					Me.SendPropertyChanged("ValvFdvB")
					Me.OnValvFdvBChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresHomoEntr", DbType:="Real")>  _
		Public Property PresHomoEntr() As System.Nullable(Of Single)
			Get
				Return Me._PresHomoEntr
			End Get
			Set
				If (Me._PresHomoEntr.Equals(value) = false) Then
					Me.OnPresHomoEntrChanging(value)
					Me.SendPropertyChanging
					Me._PresHomoEntr = value
					Me.SendPropertyChanged("PresHomoEntr")
					Me.OnPresHomoEntrChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresHomoSaida", DbType:="Real")>  _
		Public Property PresHomoSaida() As System.Nullable(Of Single)
			Get
				Return Me._PresHomoSaida
			End Get
			Set
				If (Me._PresHomoSaida.Equals(value) = false) Then
					Me.OnPresHomoSaidaChanging(value)
					Me.SendPropertyChanging
					Me._PresHomoSaida = value
					Me.SendPropertyChanged("PresHomoSaida")
					Me.OnPresHomoSaidaChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempAguaAlcool", DbType:="Real")>  _
		Public Property TempAguaAlcool() As System.Nullable(Of Single)
			Get
				Return Me._TempAguaAlcool
			End Get
			Set
				If (Me._TempAguaAlcool.Equals(value) = false) Then
					Me.OnTempAguaAlcoolChanging(value)
					Me.SendPropertyChanging
					Me._TempAguaAlcool = value
					Me.SendPropertyChanged("TempAguaAlcool")
					Me.OnTempAguaAlcoolChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva2", DbType:="Real")>  _
		Public Property Reserva2() As System.Nullable(Of Single)
			Get
				Return Me._Reserva2
			End Get
			Set
				If (Me._Reserva2.Equals(value) = false) Then
					Me.OnReserva2Changing(value)
					Me.SendPropertyChanging
					Me._Reserva2 = value
					Me.SendPropertyChanged("Reserva2")
					Me.OnReserva2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva3", DbType:="Real")>  _
		Public Property Reserva3() As System.Nullable(Of Single)
			Get
				Return Me._Reserva3
			End Get
			Set
				If (Me._Reserva3.Equals(value) = false) Then
					Me.OnReserva3Changing(value)
					Me.SendPropertyChanging
					Me._Reserva3 = value
					Me.SendPropertyChanged("Reserva3")
					Me.OnReserva3Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva4", DbType:="Real")>  _
		Public Property Reserva4() As System.Nullable(Of Single)
			Get
				Return Me._Reserva4
			End Get
			Set
				If (Me._Reserva4.Equals(value) = false) Then
					Me.OnReserva4Changing(value)
					Me.SendPropertyChanging
					Me._Reserva4 = value
					Me.SendPropertyChanged("Reserva4")
					Me.OnReserva4Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva5", DbType:="Real")>  _
		Public Property Reserva5() As System.Nullable(Of Single)
			Get
				Return Me._Reserva5
			End Get
			Set
				If (Me._Reserva5.Equals(value) = false) Then
					Me.OnReserva5Changing(value)
					Me.SendPropertyChanging
					Me._Reserva5 = value
					Me.SendPropertyChanged("Reserva5")
					Me.OnReserva5Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva6", DbType:="Real")>  _
		Public Property Reserva6() As System.Nullable(Of Single)
			Get
				Return Me._Reserva6
			End Get
			Set
				If (Me._Reserva6.Equals(value) = false) Then
					Me.OnReserva6Changing(value)
					Me.SendPropertyChanging
					Me._Reserva6 = value
					Me.SendPropertyChanged("Reserva6")
					Me.OnReserva6Changed
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FdvGravaHist")>  _
	Partial Public Class FdvGravaHist
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _FdvId As Integer
		
		Private _DataHora As String
		
		Private _PastId As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnFdvIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnFdvIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnPastIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPastIdChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FdvId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property FdvId() As Integer
			Get
				Return Me._FdvId
			End Get
			Set
				If ((Me._FdvId = value)  _
							= false) Then
					Me.OnFdvIdChanging(value)
					Me.SendPropertyChanging
					Me._FdvId = value
					Me.SendPropertyChanged("FdvId")
					Me.OnFdvIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PastId", DbType:="Int")>  _
		Public Property PastId() As System.Nullable(Of Integer)
			Get
				Return Me._PastId
			End Get
			Set
				If (Me._PastId.Equals(value) = false) Then
					Me.OnPastIdChanging(value)
					Me.SendPropertyChanging
					Me._PastId = value
					Me.SendPropertyChanged("PastId")
					Me.OnPastIdChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FdvGravaHistDados")>  _
	Partial Public Class FdvGravaHistDados
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _FdvID As Integer
		
		Private _DataHora As String
		
		Private _TempFdvPv As System.Nullable(Of Single)
		
		Private _TempFdvSp As System.Nullable(Of Single)
		
		Private _ValvFdvA As System.Nullable(Of Integer)
		
		Private _ValvFdvB As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnFdvIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnFdvIDChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnTempFdvPvChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvPvChanged()
    End Sub
    Partial Private Sub OnTempFdvSpChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvSpChanged()
    End Sub
    Partial Private Sub OnValvFdvAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnValvFdvAChanged()
    End Sub
    Partial Private Sub OnValvFdvBChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnValvFdvBChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FdvID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property FdvID() As Integer
			Get
				Return Me._FdvID
			End Get
			Set
				If ((Me._FdvID = value)  _
							= false) Then
					Me.OnFdvIDChanging(value)
					Me.SendPropertyChanging
					Me._FdvID = value
					Me.SendPropertyChanged("FdvID")
					Me.OnFdvIDChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvPv", DbType:="Real")>  _
		Public Property TempFdvPv() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvPv
			End Get
			Set
				If (Me._TempFdvPv.Equals(value) = false) Then
					Me.OnTempFdvPvChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvPv = value
					Me.SendPropertyChanged("TempFdvPv")
					Me.OnTempFdvPvChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvSp", DbType:="Real")>  _
		Public Property TempFdvSp() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvSp
			End Get
			Set
				If (Me._TempFdvSp.Equals(value) = false) Then
					Me.OnTempFdvSpChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvSp = value
					Me.SendPropertyChanged("TempFdvSp")
					Me.OnTempFdvSpChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvA", DbType:="Int")>  _
		Public Property ValvFdvA() As System.Nullable(Of Integer)
			Get
				Return Me._ValvFdvA
			End Get
			Set
				If (Me._ValvFdvA.Equals(value) = false) Then
					Me.OnValvFdvAChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvA = value
					Me.SendPropertyChanged("ValvFdvA")
					Me.OnValvFdvAChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvB", DbType:="Int")>  _
		Public Property ValvFdvB() As System.Nullable(Of Integer)
			Get
				Return Me._ValvFdvB
			End Get
			Set
				If (Me._ValvFdvB.Equals(value) = false) Then
					Me.OnValvFdvBChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvB = value
					Me.SendPropertyChanged("ValvFdvB")
					Me.OnValvFdvBChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.PastGravaHist")>  _
	Partial Public Class PastGravaHist
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _HistId As Integer
		
		Private _DataHora As String
		
		Private _PastId As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnHistIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnHistIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnPastIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPastIdChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HistId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property HistId() As Integer
			Get
				Return Me._HistId
			End Get
			Set
				If ((Me._HistId = value)  _
							= false) Then
					Me.OnHistIdChanging(value)
					Me.SendPropertyChanging
					Me._HistId = value
					Me.SendPropertyChanged("HistId")
					Me.OnHistIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14)")>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PastId", DbType:="Int")>  _
		Public Property PastId() As System.Nullable(Of Integer)
			Get
				Return Me._PastId
			End Get
			Set
				If (Me._PastId.Equals(value) = false) Then
					Me.OnPastIdChanging(value)
					Me.SendPropertyChanging
					Me._PastId = value
					Me.SendPropertyChanged("PastId")
					Me.OnPastIdChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.PastGravaHistDados")>  _
	Partial Public Class PastGravaHistDados
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _HistId As Integer
		
		Private _DataHora As String
		
		Private _Sts As System.Nullable(Of Integer)
		
		Private _RecNum As System.Nullable(Of Integer)
		
		Private _TqOrig As System.Nullable(Of Integer)
		
		Private _TqDest As System.Nullable(Of Integer)
		
		Private _PressaoEst1 As System.Nullable(Of Single)
		
		Private _PressaoEst2 As System.Nullable(Of Single)
		
		Private _TempFdvPv As System.Nullable(Of Single)
		
		Private _TempFdvSp As System.Nullable(Of Single)
		
		Private _TempFinalPast As System.Nullable(Of Single)
		
		Private _PresFinalPast As System.Nullable(Of Single)
		
		Private _ValvFdvA As System.Nullable(Of Single)
		
		Private _ValvFdvB As System.Nullable(Of Single)
		
		Private _PresHomoEntr As System.Nullable(Of Single)
		
		Private _PresHomoSaida As System.Nullable(Of Single)
		
		Private _TempAguaAlcool As System.Nullable(Of Single)
		
		Private _Reserva2 As System.Nullable(Of Single)
		
		Private _Reserva3 As System.Nullable(Of Single)
		
		Private _Reserva4 As System.Nullable(Of Single)
		
		Private _Reserva5 As System.Nullable(Of Single)
		
		Private _Reserva6 As System.Nullable(Of Single)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnHistIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnHistIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnStsChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStsChanged()
    End Sub
    Partial Private Sub OnRecNumChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRecNumChanged()
    End Sub
    Partial Private Sub OnTqOrigChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTqOrigChanged()
    End Sub
    Partial Private Sub OnTqDestChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTqDestChanged()
    End Sub
    Partial Private Sub OnPressaoEst1Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPressaoEst1Changed()
    End Sub
    Partial Private Sub OnPressaoEst2Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPressaoEst2Changed()
    End Sub
    Partial Private Sub OnTempFdvPvChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvPvChanged()
    End Sub
    Partial Private Sub OnTempFdvSpChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFdvSpChanged()
    End Sub
    Partial Private Sub OnTempFinalPastChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempFinalPastChanged()
    End Sub
    Partial Private Sub OnPresFinalPastChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresFinalPastChanged()
    End Sub
    Partial Private Sub OnValvFdvAChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnValvFdvAChanged()
    End Sub
    Partial Private Sub OnValvFdvBChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnValvFdvBChanged()
    End Sub
    Partial Private Sub OnPresHomoEntrChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresHomoEntrChanged()
    End Sub
    Partial Private Sub OnPresHomoSaidaChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnPresHomoSaidaChanged()
    End Sub
    Partial Private Sub OnTempAguaAlcoolChanging(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnTempAguaAlcoolChanged()
    End Sub
    Partial Private Sub OnReserva2Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva2Changed()
    End Sub
    Partial Private Sub OnReserva3Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva3Changed()
    End Sub
    Partial Private Sub OnReserva4Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva4Changed()
    End Sub
    Partial Private Sub OnReserva5Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva5Changed()
    End Sub
    Partial Private Sub OnReserva6Changing(value As System.Nullable(Of Single))
    End Sub
    Partial Private Sub OnReserva6Changed()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HistId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property HistId() As Integer
			Get
				Return Me._HistId
			End Get
			Set
				If ((Me._HistId = value)  _
							= false) Then
					Me.OnHistIdChanging(value)
					Me.SendPropertyChanging
					Me._HistId = value
					Me.SendPropertyChanged("HistId")
					Me.OnHistIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Sts", DbType:="Int")>  _
		Public Property Sts() As System.Nullable(Of Integer)
			Get
				Return Me._Sts
			End Get
			Set
				If (Me._Sts.Equals(value) = false) Then
					Me.OnStsChanging(value)
					Me.SendPropertyChanging
					Me._Sts = value
					Me.SendPropertyChanged("Sts")
					Me.OnStsChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecNum", DbType:="Int")>  _
		Public Property RecNum() As System.Nullable(Of Integer)
			Get
				Return Me._RecNum
			End Get
			Set
				If (Me._RecNum.Equals(value) = false) Then
					Me.OnRecNumChanging(value)
					Me.SendPropertyChanging
					Me._RecNum = value
					Me.SendPropertyChanged("RecNum")
					Me.OnRecNumChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TqOrig", DbType:="Int")>  _
		Public Property TqOrig() As System.Nullable(Of Integer)
			Get
				Return Me._TqOrig
			End Get
			Set
				If (Me._TqOrig.Equals(value) = false) Then
					Me.OnTqOrigChanging(value)
					Me.SendPropertyChanging
					Me._TqOrig = value
					Me.SendPropertyChanged("TqOrig")
					Me.OnTqOrigChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TqDest", DbType:="Int")>  _
		Public Property TqDest() As System.Nullable(Of Integer)
			Get
				Return Me._TqDest
			End Get
			Set
				If (Me._TqDest.Equals(value) = false) Then
					Me.OnTqDestChanging(value)
					Me.SendPropertyChanging
					Me._TqDest = value
					Me.SendPropertyChanged("TqDest")
					Me.OnTqDestChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PressaoEst1", DbType:="Real")>  _
		Public Property PressaoEst1() As System.Nullable(Of Single)
			Get
				Return Me._PressaoEst1
			End Get
			Set
				If (Me._PressaoEst1.Equals(value) = false) Then
					Me.OnPressaoEst1Changing(value)
					Me.SendPropertyChanging
					Me._PressaoEst1 = value
					Me.SendPropertyChanged("PressaoEst1")
					Me.OnPressaoEst1Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PressaoEst2", DbType:="Real")>  _
		Public Property PressaoEst2() As System.Nullable(Of Single)
			Get
				Return Me._PressaoEst2
			End Get
			Set
				If (Me._PressaoEst2.Equals(value) = false) Then
					Me.OnPressaoEst2Changing(value)
					Me.SendPropertyChanging
					Me._PressaoEst2 = value
					Me.SendPropertyChanged("PressaoEst2")
					Me.OnPressaoEst2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvPv", DbType:="Real")>  _
		Public Property TempFdvPv() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvPv
			End Get
			Set
				If (Me._TempFdvPv.Equals(value) = false) Then
					Me.OnTempFdvPvChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvPv = value
					Me.SendPropertyChanged("TempFdvPv")
					Me.OnTempFdvPvChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFdvSp", DbType:="Real")>  _
		Public Property TempFdvSp() As System.Nullable(Of Single)
			Get
				Return Me._TempFdvSp
			End Get
			Set
				If (Me._TempFdvSp.Equals(value) = false) Then
					Me.OnTempFdvSpChanging(value)
					Me.SendPropertyChanging
					Me._TempFdvSp = value
					Me.SendPropertyChanged("TempFdvSp")
					Me.OnTempFdvSpChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempFinalPast", DbType:="Real")>  _
		Public Property TempFinalPast() As System.Nullable(Of Single)
			Get
				Return Me._TempFinalPast
			End Get
			Set
				If (Me._TempFinalPast.Equals(value) = false) Then
					Me.OnTempFinalPastChanging(value)
					Me.SendPropertyChanging
					Me._TempFinalPast = value
					Me.SendPropertyChanged("TempFinalPast")
					Me.OnTempFinalPastChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresFinalPast", DbType:="Real")>  _
		Public Property PresFinalPast() As System.Nullable(Of Single)
			Get
				Return Me._PresFinalPast
			End Get
			Set
				If (Me._PresFinalPast.Equals(value) = false) Then
					Me.OnPresFinalPastChanging(value)
					Me.SendPropertyChanging
					Me._PresFinalPast = value
					Me.SendPropertyChanged("PresFinalPast")
					Me.OnPresFinalPastChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvA", DbType:="Real")>  _
		Public Property ValvFdvA() As System.Nullable(Of Single)
			Get
				Return Me._ValvFdvA
			End Get
			Set
				If (Me._ValvFdvA.Equals(value) = false) Then
					Me.OnValvFdvAChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvA = value
					Me.SendPropertyChanged("ValvFdvA")
					Me.OnValvFdvAChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValvFdvB", DbType:="Real")>  _
		Public Property ValvFdvB() As System.Nullable(Of Single)
			Get
				Return Me._ValvFdvB
			End Get
			Set
				If (Me._ValvFdvB.Equals(value) = false) Then
					Me.OnValvFdvBChanging(value)
					Me.SendPropertyChanging
					Me._ValvFdvB = value
					Me.SendPropertyChanged("ValvFdvB")
					Me.OnValvFdvBChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresHomoEntr", DbType:="Real")>  _
		Public Property PresHomoEntr() As System.Nullable(Of Single)
			Get
				Return Me._PresHomoEntr
			End Get
			Set
				If (Me._PresHomoEntr.Equals(value) = false) Then
					Me.OnPresHomoEntrChanging(value)
					Me.SendPropertyChanging
					Me._PresHomoEntr = value
					Me.SendPropertyChanged("PresHomoEntr")
					Me.OnPresHomoEntrChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PresHomoSaida", DbType:="Real")>  _
		Public Property PresHomoSaida() As System.Nullable(Of Single)
			Get
				Return Me._PresHomoSaida
			End Get
			Set
				If (Me._PresHomoSaida.Equals(value) = false) Then
					Me.OnPresHomoSaidaChanging(value)
					Me.SendPropertyChanging
					Me._PresHomoSaida = value
					Me.SendPropertyChanged("PresHomoSaida")
					Me.OnPresHomoSaidaChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempAguaAlcool", DbType:="Real")>  _
		Public Property TempAguaAlcool() As System.Nullable(Of Single)
			Get
				Return Me._TempAguaAlcool
			End Get
			Set
				If (Me._TempAguaAlcool.Equals(value) = false) Then
					Me.OnTempAguaAlcoolChanging(value)
					Me.SendPropertyChanging
					Me._TempAguaAlcool = value
					Me.SendPropertyChanged("TempAguaAlcool")
					Me.OnTempAguaAlcoolChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva2", DbType:="Real")>  _
		Public Property Reserva2() As System.Nullable(Of Single)
			Get
				Return Me._Reserva2
			End Get
			Set
				If (Me._Reserva2.Equals(value) = false) Then
					Me.OnReserva2Changing(value)
					Me.SendPropertyChanging
					Me._Reserva2 = value
					Me.SendPropertyChanged("Reserva2")
					Me.OnReserva2Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva3", DbType:="Real")>  _
		Public Property Reserva3() As System.Nullable(Of Single)
			Get
				Return Me._Reserva3
			End Get
			Set
				If (Me._Reserva3.Equals(value) = false) Then
					Me.OnReserva3Changing(value)
					Me.SendPropertyChanging
					Me._Reserva3 = value
					Me.SendPropertyChanged("Reserva3")
					Me.OnReserva3Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva4", DbType:="Real")>  _
		Public Property Reserva4() As System.Nullable(Of Single)
			Get
				Return Me._Reserva4
			End Get
			Set
				If (Me._Reserva4.Equals(value) = false) Then
					Me.OnReserva4Changing(value)
					Me.SendPropertyChanging
					Me._Reserva4 = value
					Me.SendPropertyChanged("Reserva4")
					Me.OnReserva4Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva5", DbType:="Real")>  _
		Public Property Reserva5() As System.Nullable(Of Single)
			Get
				Return Me._Reserva5
			End Get
			Set
				If (Me._Reserva5.Equals(value) = false) Then
					Me.OnReserva5Changing(value)
					Me.SendPropertyChanging
					Me._Reserva5 = value
					Me.SendPropertyChanged("Reserva5")
					Me.OnReserva5Changed
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reserva6", DbType:="Real")>  _
		Public Property Reserva6() As System.Nullable(Of Single)
			Get
				Return Me._Reserva6
			End Get
			Set
				If (Me._Reserva6.Equals(value) = false) Then
					Me.OnReserva6Changing(value)
					Me.SendPropertyChanging
					Me._Reserva6 = value
					Me.SendPropertyChanged("Reserva6")
					Me.OnReserva6Changed
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CipGravaHist")>  _
	Partial Public Class CipGravaHist
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _CipId As Integer
		
		Private _DataHora As String
		
		Private _Circ As String
		
		Private _Fim As System.Nullable(Of Integer)
		
		Private _RotaId As System.Nullable(Of Integer)
		
		Private _RotaDescr As String
		
		Private _RecId As System.Nullable(Of Integer)
		
		Private _RecDescr As String
		
		Private _Analise As String
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCipIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnCipIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnCircChanging(value As String)
    End Sub
    Partial Private Sub OnCircChanged()
    End Sub
    Partial Private Sub OnFimChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFimChanged()
    End Sub
    Partial Private Sub OnRotaIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRotaIdChanged()
    End Sub
    Partial Private Sub OnRotaDescrChanging(value As String)
    End Sub
    Partial Private Sub OnRotaDescrChanged()
    End Sub
    Partial Private Sub OnRecIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRecIdChanged()
    End Sub
    Partial Private Sub OnRecDescrChanging(value As String)
    End Sub
    Partial Private Sub OnRecDescrChanged()
    End Sub
    Partial Private Sub OnAnaliseChanging(value As String)
    End Sub
    Partial Private Sub OnAnaliseChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CipId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property CipId() As Integer
			Get
				Return Me._CipId
			End Get
			Set
				If ((Me._CipId = value)  _
							= false) Then
					Me.OnCipIdChanging(value)
					Me.SendPropertyChanging
					Me._CipId = value
					Me.SendPropertyChanged("CipId")
					Me.OnCipIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14)")>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Circ", DbType:="NVarChar(2)")>  _
		Public Property Circ() As String
			Get
				Return Me._Circ
			End Get
			Set
				If (String.Equals(Me._Circ, value) = false) Then
					Me.OnCircChanging(value)
					Me.SendPropertyChanging
					Me._Circ = value
					Me.SendPropertyChanged("Circ")
					Me.OnCircChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fim", DbType:="Int")>  _
		Public Property Fim() As System.Nullable(Of Integer)
			Get
				Return Me._Fim
			End Get
			Set
				If (Me._Fim.Equals(value) = false) Then
					Me.OnFimChanging(value)
					Me.SendPropertyChanging
					Me._Fim = value
					Me.SendPropertyChanged("Fim")
					Me.OnFimChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RotaId", DbType:="Int")>  _
		Public Property RotaId() As System.Nullable(Of Integer)
			Get
				Return Me._RotaId
			End Get
			Set
				If (Me._RotaId.Equals(value) = false) Then
					Me.OnRotaIdChanging(value)
					Me.SendPropertyChanging
					Me._RotaId = value
					Me.SendPropertyChanged("RotaId")
					Me.OnRotaIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RotaDescr", DbType:="NVarChar(50)")>  _
		Public Property RotaDescr() As String
			Get
				Return Me._RotaDescr
			End Get
			Set
				If (String.Equals(Me._RotaDescr, value) = false) Then
					Me.OnRotaDescrChanging(value)
					Me.SendPropertyChanging
					Me._RotaDescr = value
					Me.SendPropertyChanged("RotaDescr")
					Me.OnRotaDescrChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecId", DbType:="Int")>  _
		Public Property RecId() As System.Nullable(Of Integer)
			Get
				Return Me._RecId
			End Get
			Set
				If (Me._RecId.Equals(value) = false) Then
					Me.OnRecIdChanging(value)
					Me.SendPropertyChanging
					Me._RecId = value
					Me.SendPropertyChanged("RecId")
					Me.OnRecIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecDescr", DbType:="NVarChar(50)")>  _
		Public Property RecDescr() As String
			Get
				Return Me._RecDescr
			End Get
			Set
				If (String.Equals(Me._RecDescr, value) = false) Then
					Me.OnRecDescrChanging(value)
					Me.SendPropertyChanging
					Me._RecDescr = value
					Me.SendPropertyChanged("RecDescr")
					Me.OnRecDescrChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Analise", DbType:="NVarChar(500)")>  _
		Public Property Analise() As String
			Get
				Return Me._Analise
			End Get
			Set
				If (String.Equals(Me._Analise, value) = false) Then
					Me.OnAnaliseChanging(value)
					Me.SendPropertyChanging
					Me._Analise = value
					Me.SendPropertyChanged("Analise")
					Me.OnAnaliseChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CipGravaHistDados")>  _
	Partial Public Class CipGravaHistDados
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _CipId As Integer
		
		Private _DataHora As String
		
		Private _Cond As System.Nullable(Of Double)
		
		Private _Temp As System.Nullable(Of Double)
		
		Private _Vazao As System.Nullable(Of Double)
		
		Private _Blk As System.Nullable(Of Integer)
		
		Private _Passo As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCipIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnCipIdChanged()
    End Sub
    Partial Private Sub OnDataHoraChanging(value As String)
    End Sub
    Partial Private Sub OnDataHoraChanged()
    End Sub
    Partial Private Sub OnCondChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnCondChanged()
    End Sub
    Partial Private Sub OnTempChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnTempChanged()
    End Sub
    Partial Private Sub OnVazaoChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnVazaoChanged()
    End Sub
    Partial Private Sub OnBlkChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBlkChanged()
    End Sub
    Partial Private Sub OnPassoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPassoChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CipId", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
		Public Property CipId() As Integer
			Get
				Return Me._CipId
			End Get
			Set
				If ((Me._CipId = value)  _
							= false) Then
					Me.OnCipIdChanging(value)
					Me.SendPropertyChanging
					Me._CipId = value
					Me.SendPropertyChanged("CipId")
					Me.OnCipIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataHora", DbType:="NVarChar(14) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property DataHora() As String
			Get
				Return Me._DataHora
			End Get
			Set
				If (String.Equals(Me._DataHora, value) = false) Then
					Me.OnDataHoraChanging(value)
					Me.SendPropertyChanging
					Me._DataHora = value
					Me.SendPropertyChanged("DataHora")
					Me.OnDataHoraChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cond", DbType:="Float")>  _
		Public Property Cond() As System.Nullable(Of Double)
			Get
				Return Me._Cond
			End Get
			Set
				If (Me._Cond.Equals(value) = false) Then
					Me.OnCondChanging(value)
					Me.SendPropertyChanging
					Me._Cond = value
					Me.SendPropertyChanged("Cond")
					Me.OnCondChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Temp", DbType:="Float")>  _
		Public Property Temp() As System.Nullable(Of Double)
			Get
				Return Me._Temp
			End Get
			Set
				If (Me._Temp.Equals(value) = false) Then
					Me.OnTempChanging(value)
					Me.SendPropertyChanging
					Me._Temp = value
					Me.SendPropertyChanged("Temp")
					Me.OnTempChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Vazao", DbType:="Float")>  _
		Public Property Vazao() As System.Nullable(Of Double)
			Get
				Return Me._Vazao
			End Get
			Set
				If (Me._Vazao.Equals(value) = false) Then
					Me.OnVazaoChanging(value)
					Me.SendPropertyChanging
					Me._Vazao = value
					Me.SendPropertyChanged("Vazao")
					Me.OnVazaoChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Blk", DbType:="Int")>  _
		Public Property Blk() As System.Nullable(Of Integer)
			Get
				Return Me._Blk
			End Get
			Set
				If (Me._Blk.Equals(value) = false) Then
					Me.OnBlkChanging(value)
					Me.SendPropertyChanging
					Me._Blk = value
					Me.SendPropertyChanged("Blk")
					Me.OnBlkChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Passo", DbType:="Int")>  _
		Public Property Passo() As System.Nullable(Of Integer)
			Get
				Return Me._Passo
			End Get
			Set
				If (Me._Passo.Equals(value) = false) Then
					Me.OnPassoChanging(value)
					Me.SendPropertyChanging
					Me._Passo = value
					Me.SendPropertyChanged("Passo")
					Me.OnPassoChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
